### PR TITLE
#26  Fixed toggling of buttons problem

### PR DESCRIPTION
**Pull request by rt1301**
A solution to the toggling buttons problem. I have changed the handleExpandClick option so that only the clicked card's content are visible

### CODE REVIEW

**Comment by suraj-sloth** [comment]
This PR fails the netlify deploy checks. Please pull the latest changes and commit on this PR/ create a new one. Also attach images/gif related to this patch.

**Comment by rt1301** [comment]
Can you provide the permission to check the logs of Netlify so that I can check what errors are occurring?

**Comment by suraj-sloth** [comment]
The issue regarding the netlify deploy checks is solved. Just pull the respective changes and commit to this PR :)

**Comment by rt1301** [comment]
So, should I make the PR once again? coz here it still shows that the checks have failed

**Comment by rt1301** [comment]
How is the netlify deploy checks error are corrected?

**Comment by suraj-sloth** [comment]
@rt1301 Yes please proceed with another PR. Netlify deploy checks will fail if you have any warnings in your local build.

**Comment by suraj-sloth** [comment]
Hey, this is the deploy preview of your PR [https://deploy-preview-33--hncc-contest.netlify.app/](https://deploy-preview-33--hncc-contest.netlify.app/).It seems that the problem isn't resolved yet. It would be great if the clicked card only expands, not the the others.

**Comment by rt1301** [comment]
I tried fixing that error, by using a Accordian as well as changing the onClick function. Both are giving this same result. This is some issue related to the the material UI react library

**Pull request merged**
